#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout